controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

readNote:
    path: /api/v1/read_note
    methods: GET
    controller: App\Controller\NoteController::read

creatNote:
    path: /api/v1/create_note
    methods: POST
    controller: App\Controller\NoteController::create

updateNote:
    path: /api/v1/update_note
    methods: POST
    controller: App\Controller\NoteController::update