services:
  to_do_frontend:
    container_name: to_do_frontend
    build:
      context: ../docker/node
      dockerfile: Dockerfile
    volumes:
      - ../to_do_frontend:/var/www/to_do_frontend
  to_do_backend:
    container_name: to_do_backend
    build:
      context: ../docker/php
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ./:/var/www/to_do_backend
  to_do_nginx:
    container_name: to_do_nginx
    build:
      context: ../docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ../docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/to_do_backend
      - ../to_do_frontend:/var/www/to_do_frontend
    ports:
      - ${NGINX_PORT:-80}:80
  postgres:
    container_name: postgres
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-root}
    volumes:
      - ./database_data:/var/lib/postgresql/data:rw
    ports:
      - ${DB_PORT:-5432}:5432
