services:
  to_do_frontend:
    container_name: to_do_frontend
    build:
      context: ./../docker/node
      dockerfile: Dockerfile
    volumes:
      - ../to_do_frontend:/var/www/to_do_frontend
    ports:
      - ${NODE_PORT}:5173
  to_do_backend:
    container_name: to_do_backend
    build:
      context: ../docker/php
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ./:/var/www/to_do_backend
  to_do_nginx:
    container_name: to_do_nginx
    build:
      context: ../docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ../docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/to_do_backend
      - ../to_do_frontend:/var/www/to_do_frontend
    ports:
      - ${NGINX_PORT}:80
  to_do_mysql:
    container_name: to_do_mysql
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306